### ISSUE TITLE
请问Linux要怎么搭建这个应用？这里抛出一个错误

### ISSUE THREAD

**Issue by kurt-steiner** [oleg-agapov/flask-vue-spa#9]
我用的是ubuntu18.04LS,`flask run`的时候抛出一个错误
```python3
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 7, in <module>
    from flask.cli import main
  File "/home/steiner/.local/lib/python3.6/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask
  File "/home/steiner/.local/lib/python3.6/site-packages/flask/app.py", line 69, in <module>
    from .wrappers import Request
  File "/home/steiner/.local/lib/python3.6/site-packages/flask/wrappers.py", line 14, in <module>
    from werkzeug.wrappers.json import JSONMixin as _JSONMixin
ModuleNotFoundError: No module named 'werkzeug.wrappers.json'; 'werkzeug.wrappers' is not a package
```
这个怎么解决

**Comment by Orenoid** [comment]
把werkzeug版本改成0.15.4试试
https://stackoverflow.com/questions/56933523/apache-airflow-airflow-initdb-throws-modulenotfounderror-no-module-named-wer
